docs: Update UserGuide
AY2324S2-CS2103T-W09-2/tp pull request #116
Opened 2024-04-10 22:48 UTC by menatahari

2024-04-11 01:44 UTC, yeoshuheng requested changes
Some nits, sorry about that!

2024-04-11 01:44 UTC, yeoshuheng commented on docs/UserGuide.md
> +
Maybe it would be good to add a tip box warning on the execution of the clear command.

2024-04-11 01:44 UTC, yeoshuheng commented on docs/UserGuide.md
> +* Currently selected startup card will appear blue!
Would it be good for some image or graphics to come together with this? I'm worried that solely saying "in blue" might be confusing for users, but I'm not too sure either.

2024-04-11 15:06 UTC, dwangwk approved these changes
LGTM!

2024-04-12 04:06 UTC, yeoshuheng approved these changes
lgtm

2024-04-12 04:06 UTC, merged